
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class return_actions
{

    public int return_actions_id { get; set; }

    public Nullable<int> reaturn_id { get; set; }

    public string attachment { get; set; }

    public Nullable<int> created_by { get; set; }

    public Nullable<System.DateTime> created_datetime { get; set; }

    public string note { get; set; }

    public string status { get; set; }

}

}
